// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyohdrliebpgxuzycrov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95b2hkcmxpZWJwZ3h1enljcm92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0OTg0OTYsImV4cCI6MjA2MjA3NDQ5Nn0.eWXUxlFsJ_CZqbOrVGh-_RTIiozQkLj7CeC-95fN_GE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);